# Generated by Django 4.0.5 on 2022-06-12 13:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='img',
            field=models.ImageField(default='', upload_to=accounts.models.org_img_upload, verbose_name='Изображение организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название организации'),
            preserve_default=False,
        ),
    ]
