# Generated by Django 4.0.5 on 2022-06-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=None, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
