# Generated by Django 4.0.5 on 2022-06-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_birth_date_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False, verbose_name='Статус волонтёра'),
        ),
    ]
