# Generated by Django 4.0.5 on 2022-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organization_options_alter_volunteer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=True, max_length=75, null=True),
        ),
    ]
