# Generated by Django 4.0.5 on 2022-06-11 18:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='accounts/avatars/default.svg', upload_to=accounts.models.avatar_directory_path, verbose_name='Аватарка'),
        ),
    ]
