# Generated by Django 4.0.5 on 2022-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Скилл',
                'verbose_name_plural': 'Скиллы',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='age_min',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Минимальный возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Test', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_people_count',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Максимальное количество людей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='service',
            field=models.TextField(blank=True, verbose_name='Сервис'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='vacancies.skill', verbose_name='Требования'),
        ),
    ]
