# Generated by Django 4.0.5 on 2022-06-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_organization_options_alter_volunteer_options'),
        ('vacancies', '0002_skill_vacancy_age_max_vacancy_age_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
