# Generated by Django 4.0.5 on 2022-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округа',
            },
        ),
    ]
