# Generated by Django 4.0.5 on 2022-06-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='county',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vacancies.county', verbose_name='Округ'),
            preserve_default=False,
        ),
    ]
