# Generated by Django 4.0.5 on 2022-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='title',
            field=models.CharField(max_length=75, unique=True, verbose_name='Название'),
        ),
    ]
