# Generated by Django 4.0.5 on 2022-06-12 07:39

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='time_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время завершения'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time_start',
            field=models.DateTimeField(default='1999-01-01', verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=vacancies.models.vacancy_img_upload_path, verbose_name='Изображение'),
        ),
    ]
